# Generated by Django 3.0.5 on 2020-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_phone', models.CharField(max_length=100)),
                ('your_email', models.EmailField(max_length=100)),
                ('your_address', models.CharField(max_length=300)),
                ('your_scheldule', models.CharField(max_length=100)),
                ('your_time', models.CharField(max_length=100)),
                ('your_message', models.TextField(max_length=100)),
            ],
        ),
    ]
